name: build flowaccount-workshop
on: 
  push:
    branches:
      - main
      - 'feat/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
jobs:
  main:
    runs-on: ubuntu
    permissions:
      contents: 'read'
      actions: 'write'
      id-token: 'write'
    defaults:
      run:
        working-directory: ${{ inputs.working-directory || github.workspace }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      if: always()
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::765141697745:role/GithubActionAssumeRole
        aws-region: ap-southeast-1
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'
    - name: github.workspace path 
      run: echo ${{ github.workspace }}
    - name: Get PR number
      id: action
      uses: kamatama41/get-pr-number-action@v0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: docker build
      run: |
        cd apps/api/flowaccount-workshop
        ls
        docker build . -t 765141697745.dkr.ecr.ap-southeast-1.amazonaws.com/flowaccount/public-workshop-sandbox:latest-public-workshop-sandbox
    - name: docker push
      run: |
        docker push 765141697745.dkr.ecr.ap-southeast-1.amazonaws.com/flowaccount/public-workshop-sandbox:latest-public-workshop-sandbox